###one way test
GET http://localhost:3000/flights/search-one-way
Content-Type: application/json

{
  "fromEntityId": "NYCA",
  "toEntityId": "LAXA",
  "departDate": "2024-08-12",
  "adults": 1,
  "children": 0,
  "cabinClass": "economy"
}

###roundtrip test
GET http://localhost:3000/flights/search-roundtrip
Content-Type: application/json

{
  "fromEntityId": "TPE",
  "toEntityId": "LAXA",
  "departDate": "2024-08-12",
  "returnDate": "2024-08-13",
  "adults": 1,
  "children": 0,
  "cabinClass": "economy",
  "sorted": true
}

###add money one way test
GET http://localhost:3000/flights/search-one-way
Content-Type: application/json

{
  "fromEntityId": "NYCA",
  "toEntityId": "LAXA",
  "departDate": "2024-08-12",
  "adults": 1,
  "children": 0,
  "cabinClass": "economy",
  "sorted": true
}

###max and min test
GET http://localhost:3000/flights/search-one-way
Content-Type: application/json

{
  "fromEntityId": "NYCA",
  "toEntityId": "LAXA",
  "departDate": "2024-08-12",
  "adults": 1,
  "children": 0,
  "cabinClass": "economy",
  "minPrice": "0",
  "maxPrice": "500",
  "sorted": true
}

###duration time test
GET http://localhost:3000/flights/search-one-way
Content-Type: application/json

{
  "fromEntityId": "NYCA",
  "toEntityId": "LAXA",
  "departDate": "2024-08-12",
  "adults": 1,
  "children": 0,
  "cabinClass": "economy",
  "minPrice": "0",
  "maxPrice": "500",
  "sorted": true,
  "minDuration": 0,
  "maxDuration": 800
}

###departure time test
GET http://localhost:3000/flights/search-one-way
Content-Type: application/json

{
  "fromEntityId": "NYCA",
  "toEntityId": "LAXA",
  "departDate": "2024-08-12",
  "adults": 1,
  "children": 0,
  "cabinClass": "economy",
  "minPrice": "0",
  "maxPrice": "500",
  "sorted": true,
  "minDuration": 0,
  "maxDuration": 800,
  "minDeparture":  "2024-08-12T00:00:00",
  "maxDeparture":  "2024-08-12T12:00:00"
}

