###one way test
GET http://localhost:3000/flights/search-one-way
Content-Type: application/json

{
  "fromEntityId": "NYCA",
  "toEntityId": "LAXA",
  "departDate": "2024-08-12",
  "adults": 1,
  "children": 0,
  "cabinClass": "economy"
}

###roundtrip test
GET http://localhost:3000/flights/search-roundtrip
Content-Type: application/json

{
  "fromEntityId": "NYCA",
  "toEntityId": "LAXA",
  "departDate": "2024-08-12",
  "returnDate": "2024-08-16",
  "adults": 1,
  "children": 0,
  "cabinClass": "economy"
}

###add money one way test
GET http://localhost:3000/flights/search-one-way
Content-Type: application/json

{
  "fromEntityId": "NYCA",
  "toEntityId": "LAXA",
  "departDate": "2024-08-12",
  "adults": 1,
  "children": 0,
  "cabinClass": "economy",
  "sorted": true
}

###max and min test
GET http://localhost:3000/flights/search-one-way
Content-Type: application/json

{
  "fromEntityId": "NYCA",
  "toEntityId": "LAXA",
  "departDate": "2024-08-12",
  "adults": 1,
  "children": 0,
  "cabinClass": "economy",
  "minPrice": "0",
  "maxPrice": "290",
  "sorted": true
}

